# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Internal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#fabian es puto 

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inicio_Form(object):
    def setupUi(self, Inicio_Form):
        Inicio_Form.setObjectName("Inicio_Form")
        Inicio_Form.resize(800, 600)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Inicio_Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(290, 380, 228, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Continuar_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Continuar_pushButton.setObjectName("Continuar_pushButton")
        self.horizontalLayout.addWidget(self.Continuar_pushButton)
        self.Salir_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Salir_pushButton.setObjectName("Salir_pushButton")
        self.horizontalLayout.addWidget(self.Salir_pushButton)

        self.retranslateUi(Inicio_Form)
        QtCore.QMetaObject.connectSlotsByName(Inicio_Form)

    def retranslateUi(self, Inicio_Form):
        _translate = QtCore.QCoreApplication.translate
        Inicio_Form.setWindowTitle(_translate("Inicio_Form", "Form"))
        self.Continuar_pushButton.setText(_translate("Inicio_Form", "Continuar"))
        self.Salir_pushButton.setText(_translate("Inicio_Form", "Salir"))

class Ui_Inicio_Form2(QtWidgets.QWidget):
    def setupUi(self):
        self.resize(800,600)
        self.horizontalLayoutWidget = QtWidgets.QWidget()
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(290, 380, 228, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Continuar_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Continuar_pushButton.setObjectName("Continuar_pushButton")
        self.horizontalLayout.addWidget(self.Continuar_pushButton)
        self.Salir_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Salir_pushButton.setObjectName("Salir_pushButton")
        self.horizontalLayout.addWidget(self.Salir_pushButton)
        #self.Continuar_pushButton.setText(( "Continuar"))
        #self.Salir_pushButton.setText(("Salir"))

        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inicio_Form = QtWidgets.QWidget()
    ui = Ui_Inicio_Form2()
    ui.setupUi(Inicio_Form)
    Inicio_Form.show()
    sys.exit(app.exec_())
