# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Form(object):
    def setupUi(self, Login_Form):
        Login_Form.setObjectName("Login_Form")
        Login_Form.resize(800, 600)
        self.InicioDSesion_label = QtWidgets.QLabel(Login_Form)
        self.InicioDSesion_label.setGeometry(QtCore.QRect(300, 220, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.InicioDSesion_label.setFont(font)
        self.InicioDSesion_label.setAlignment(QtCore.Qt.AlignCenter)
        self.InicioDSesion_label.setObjectName("InicioDSesion_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Login_Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 260, 251, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Correo_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Correo_lineEdit.setFont(font)
        self.Correo_lineEdit.setText("")
        self.Correo_lineEdit.setReadOnly(False)
        self.Correo_lineEdit.setClearButtonEnabled(False)
        self.Correo_lineEdit.setObjectName("Correo_lineEdit")
        self.verticalLayout.addWidget(self.Correo_lineEdit)
        self.Contrasena_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Contrasena_lineEdit.setFont(font)
        self.Contrasena_lineEdit.setText("")
        self.Contrasena_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Contrasena_lineEdit.setReadOnly(False)
        self.Contrasena_lineEdit.setObjectName("Contrasena_lineEdit")
        self.verticalLayout.addWidget(self.Contrasena_lineEdit)
        self.Ingresar_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Ingresar_pushButton.setFont(font)
        self.Ingresar_pushButton.setObjectName("Ingresar_pushButton")
        self.verticalLayout.addWidget(self.Ingresar_pushButton)
        self.Registrar_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Registrar_pushButton.setFont(font)
        self.Registrar_pushButton.setObjectName("Registrar_pushButton")
        self.verticalLayout.addWidget(self.Registrar_pushButton)

        self.retranslateUi(Login_Form)
        QtCore.QMetaObject.connectSlotsByName(Login_Form)

    def retranslateUi(self, Login_Form):
        _translate = QtCore.QCoreApplication.translate
        Login_Form.setWindowTitle(_translate("Login_Form", "Form"))
        self.InicioDSesion_label.setText(_translate("Login_Form", "Inicio de sesion "))
        self.Correo_lineEdit.setPlaceholderText(_translate("Login_Form", "Correo"))
        self.Contrasena_lineEdit.setPlaceholderText(_translate("Login_Form", "Contrasena"))
        self.Ingresar_pushButton.setText(_translate("Login_Form", "Ingresar"))
        self.Registrar_pushButton.setText(_translate("Login_Form", "Registrar"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Form = QtWidgets.QWidget()
    ui = Ui_Login_Form()
    ui.setupUi(Login_Form)
    Login_Form.show()
    sys.exit(app.exec_())
