# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interal_Form(object):
    def setupUi(self, Interal_Form):
        Interal_Form.setObjectName("Interal_Form")
        Interal_Form.resize(800, 600)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Interal_Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 180, 191, 321))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ImagenesImport_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.ImagenesImport_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ImagenesImport_label.setObjectName("ImagenesImport_label")
        self.verticalLayout_4.addWidget(self.ImagenesImport_label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ImagenSup_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.ImagenSup_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ImagenSup_label.setObjectName("ImagenSup_label")
        self.verticalLayout_3.addWidget(self.ImagenSup_label)
        self.ImagenSup_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.ImagenSup_pushButton.setObjectName("ImagenSup_pushButton")
        self.verticalLayout_3.addWidget(self.ImagenSup_pushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ImagenLat_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.ImagenLat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ImagenLat_label.setObjectName("ImagenLat_label")
        self.verticalLayout.addWidget(self.ImagenLat_label)
        self.ImagenLat_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.ImagenLat_pushButton.setObjectName("ImagenLat_pushButton")
        self.verticalLayout.addWidget(self.ImagenLat_pushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Tiempo_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Tiempo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Tiempo_label.setObjectName("Tiempo_label")
        self.verticalLayout_2.addWidget(self.Tiempo_label)
        self.Tiempo_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.Tiempo_spinBox.setObjectName("Tiempo_spinBox")
        self.verticalLayout_2.addWidget(self.Tiempo_spinBox)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)

        self.retranslateUi(Interal_Form)
        QtCore.QMetaObject.connectSlotsByName(Interal_Form)

    def retranslateUi(self, Interal_Form):
        _translate = QtCore.QCoreApplication.translate
        Interal_Form.setWindowTitle(_translate("Interal_Form", "Form"))
        self.ImagenesImport_label.setText(_translate("Interal_Form", "Importar Imagenes"))
        self.ImagenSup_label.setText(_translate("Interal_Form", "Imagen Supeficial "))
        self.ImagenSup_pushButton.setText(_translate("Interal_Form", "Capturar"))
        self.ImagenLat_label.setText(_translate("Interal_Form", "Imagen Lateral"))
        self.ImagenLat_pushButton.setText(_translate("Interal_Form", "Capturar"))
        self.Tiempo_label.setText(_translate("Interal_Form", "Tiempo (Minutos)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Interal_Form = QtWidgets.QWidget()
    ui = Ui_Interal_Form()
    ui.setupUi(Interal_Form)
    Interal_Form.show()
    sys.exit(app.exec_())
