# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registro_SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Stylesheet_format import Stylesheet


class Ui_Register_Form(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(1440, 900)

        self.return_pushButton = QtWidgets.QPushButton(Register,icon = QtGui.QIcon(QtGui.QPixmap("Return_icon.svg")))
        self.return_pushButton.setGeometry(QtCore.QRect(20, 14, 69, 75))
        self.return_pushButton.setObjectName("return_pushButton")

        self.label = QtWidgets.QLabel(Register)
        self.label.setGeometry(QtCore.QRect(91, 21, 376, 69))
        self.label.setObjectName("label")

        self.lineEdit = QtWidgets.QLineEdit(Register)
        self.lineEdit.setGeometry(QtCore.QRect(54, 163, 260, 36))
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(Register)
        self.lineEdit_2.setGeometry(QtCore.QRect(324, 163, 1061, 36))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(Register)
        self.lineEdit_3.setGeometry(QtCore.QRect(55, 256, 1331, 36))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.lineEdit_4 = QtWidgets.QLineEdit(Register)
        self.lineEdit_4.setGeometry(QtCore.QRect(55, 349, 1331, 36))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.lineEdit_5 = QtWidgets.QLineEdit(Register)
        self.lineEdit_5.setGeometry(QtCore.QRect(55, 535, 1331, 36))
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.lineEdit_6 = QtWidgets.QLineEdit(Register)
        self.lineEdit_6.setGeometry(QtCore.QRect(55, 442, 1331, 36))
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.checkBox = QtWidgets.QCheckBox(Register)
        self.checkBox.setGeometry(QtCore.QRect(54, 642, 86, 20))
        self.checkBox.setObjectName("checkBox")
        
        self.pushButton_2 = QtWidgets.QPushButton(Register)
        self.pushButton_2.setGeometry(QtCore.QRect(28, 790, 1384, 44))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label_2 = QtWidgets.QLabel(Register)
        self.label_2.setGeometry(QtCore.QRect(591, 854, 170, 16))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Register)
        self.label_3.setGeometry(QtCore.QRect(771, 854, 100, 22))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Form"))
        self.label.setText(_translate("Register", "TextLabel"))
        self.checkBox.setText(_translate("Register", "By Signing up"))
        self.pushButton_2.setText(_translate("Register", "PushButton"))
        self.label_2.setText(_translate("Register", "TextLabel"))
        self.label_3.setText(_translate("Register", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Register = QtWidgets.QWidget()
    ui = Ui_Register_Form()
    ui.setupUi(Register)
    Register.show()
    sys.exit(app.exec_())
