# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubVentanaTipoIMG.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageType_Form(object):
    def setupUi(self, ImageType_Form):
        ImageType_Form.setObjectName("ImageType_Form")
        ImageType_Form.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(ImageType_Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 130, 338, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TipoDeImagen_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.TipoDeImagen_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TipoDeImagen_label.setObjectName("TipoDeImagen_label")
        self.verticalLayout.addWidget(self.TipoDeImagen_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ImagenMues_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ImagenMues_pushButton.setObjectName("ImagenMues_pushButton")
        self.horizontalLayout.addWidget(self.ImagenMues_pushButton)
        self.ImagenSuperficie_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ImagenSuperficie_pushButton.setObjectName("ImagenSuperficie_pushButton")
        self.horizontalLayout.addWidget(self.ImagenSuperficie_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ImageType_Form)
        QtCore.QMetaObject.connectSlotsByName(ImageType_Form)

    def retranslateUi(self, ImageType_Form):
        _translate = QtCore.QCoreApplication.translate
        ImageType_Form.setWindowTitle(_translate("ImageType_Form", "Form"))
        self.TipoDeImagen_label.setText(_translate("ImageType_Form", "Tipo de Imagen"))
        self.ImagenMues_pushButton.setText(_translate("ImageType_Form", "Imagen de Muestra"))
        self.ImagenSuperficie_pushButton.setText(_translate("ImageType_Form", "Imagen de Superficie"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImageType_Form = QtWidgets.QWidget()
    ui = Ui_ImageType_Form()
    ui.setupUi(ImageType_Form)
    ImageType_Form.show()
    sys.exit(app.exec_())
