# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubVentanaSuperficie.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageSup_Form(object):
    def setupUi(self, ImageSup_Form):
        ImageSup_Form.setObjectName("ImageSup_Form")
        ImageSup_Form.resize(400, 300)
        self.widget = QtWidgets.QWidget(ImageSup_Form)
        self.widget.setGeometry(QtCore.QRect(70, 70, 249, 129))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.MaterialSup_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.MaterialSup_lineEdit.setObjectName("MaterialSup_lineEdit")
        self.gridLayout.addWidget(self.MaterialSup_lineEdit, 1, 1, 1, 1)
        self.DimMat_label = QtWidgets.QLabel(self.widget)
        self.DimMat_label.setObjectName("DimMat_label")
        self.gridLayout.addWidget(self.DimMat_label, 2, 0, 1, 1)
        self.IDSup_label = QtWidgets.QLabel(self.widget)
        self.IDSup_label.setObjectName("IDSup_label")
        self.gridLayout.addWidget(self.IDSup_label, 0, 0, 1, 1)
        self.MaterialSup_label = QtWidgets.QLabel(self.widget)
        self.MaterialSup_label.setObjectName("MaterialSup_label")
        self.gridLayout.addWidget(self.MaterialSup_label, 1, 0, 1, 1)
        self.IDSup_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.IDSup_lineEdit.setObjectName("IDSup_lineEdit")
        self.gridLayout.addWidget(self.IDSup_lineEdit, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ImageSup_Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 230, 251, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(ImageSup_Form)
        QtCore.QMetaObject.connectSlotsByName(ImageSup_Form)

    def retranslateUi(self, ImageSup_Form):
        _translate = QtCore.QCoreApplication.translate
        ImageSup_Form.setWindowTitle(_translate("ImageSup_Form", "Form"))
        self.DimMat_label.setText(_translate("ImageSup_Form", "Dimenciones"))
        self.IDSup_label.setText(_translate("ImageSup_Form", "ID: Superficie"))
        self.MaterialSup_label.setText(_translate("ImageSup_Form", "Material"))
        self.pushButton_2.setText(_translate("ImageSup_Form", "Explorar"))
        self.pushButton.setText(_translate("ImageSup_Form", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImageSup_Form = QtWidgets.QWidget()
    ui = Ui_ImageSup_Form()
    ui.setupUi(ImageSup_Form)
    ImageSup_Form.show()
    sys.exit(app.exec_())
