# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Stylesheet_format import Stylesheet

class Ui_imageUpload_Form(object):
    def setupUi(self, imageUpload_Form):
        imageUpload_Form.setObjectName("imageUpload_Form")
        imageUpload_Form.resize(1440, 900)

        self.BiotextureX_Label = QtWidgets.QLabel(imageUpload_Form)
        self.BiotextureX_Label.setGeometry(QtCore.QRect(121, 24, 298, 68))
        self.BiotextureX_Label.setObjectName("BiotextureX_Label")
        self.BiotextureX_Label.setStyleSheet(Stylesheet)

        self.typeImage_label = QtWidgets.QLabel(imageUpload_Form)
        self.typeImage_label.setGeometry(QtCore.QRect(372, 126, 695, 69))
        self.typeImage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.typeImage_label.setObjectName("typeImage_label")
        self.typeImage_label.setStyleSheet(Stylesheet)

        self.topView_label = QtWidgets.QLabel(imageUpload_Form)
        self.topView_label.setGeometry(QtCore.QRect(232, 234, 280, 26))
        self.topView_label.setAlignment(QtCore.Qt.AlignCenter)
        self.topView_label.setObjectName("topView_label")
        self.topView_label.setStyleSheet(Stylesheet)

        self.sideView_label = QtWidgets.QLabel(imageUpload_Form)
        self.sideView_label.setGeometry(QtCore.QRect(926, 234, 280, 26))
        self.sideView_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sideView_label.setObjectName("sideView_label")
        self.sideView_label.setStyleSheet(Stylesheet)

        self.topUploadImage_pushButton = QtWidgets.QPushButton(imageUpload_Form)
        self.topUploadImage_pushButton.setGeometry(QtCore.QRect(181,321, 389,102))
        self.topUploadImage_pushButton.setObjectName("topUploadImage_pushButton")
        self.topUploadImage_pushButton.setStyleSheet(Stylesheet)

        self.sideUploadImage_pushButton = QtWidgets.QPushButton(imageUpload_Form)
        self.sideUploadImage_pushButton.setGeometry(QtCore.QRect(872,321, 389,102))
        self.sideUploadImage_pushButton.setObjectName("sideUploadImage_pushButton")
        self.sideUploadImage_pushButton.setStyleSheet(Stylesheet)

        self.UpLoad_pushButton = QtWidgets.QPushButton(imageUpload_Form,icon = QtGui.QIcon(QtGui.QPixmap("PyQt_Images/Upload_icon2.svg")))
        self.UpLoad_pushButton.setIconSize(QtCore.QSize(50, 50))
        self.UpLoad_pushButton.setGeometry(QtCore.QRect(106, 798, 213, 89))
        self.UpLoad_pushButton.setObjectName("UpLoad_pushButton")
        self.UpLoad_pushButton.setStyleSheet(Stylesheet)

        self.Home_pushButton = QtWidgets.QPushButton(imageUpload_Form, icon = QtGui.QIcon(QtGui.QPixmap("PyQt_Images/House_icon.svg")))
        self.Home_pushButton.setIconSize(QtCore.QSize(66, 66))
        self.Home_pushButton.setGeometry(QtCore.QRect(601, 798, 213, 89))
        self.Home_pushButton.setObjectName("Home_pushButton")
        self.Home_pushButton.setStyleSheet(Stylesheet)

        self.User_pushButton = QtWidgets.QPushButton(imageUpload_Form,icon = QtGui.QIcon(QtGui.QPixmap("PyQt_Images/User_icon.svg")))
        self.User_pushButton.setIconSize(QtCore.QSize(66, 66))
        self.User_pushButton.setGeometry(QtCore.QRect(1121, 798, 213, 89))
        self.User_pushButton.setObjectName("User_pushButton")
        self.User_pushButton.setStyleSheet(Stylesheet)


        self.retranslateUi(imageUpload_Form)
        QtCore.QMetaObject.connectSlotsByName(imageUpload_Form)

    def retranslateUi(self, imageUpload_Form):
        _translate = QtCore.QCoreApplication.translate
        imageUpload_Form.setWindowTitle(_translate("imageUpload_Form", "Form"))
        self.BiotextureX_Label.setText(_translate("imageUpload_Form", "BioTextureX"))
        self.typeImage_label.setText(_translate("imageUpload_Form", "Import each type of image"))
        self.topView_label.setText(_translate("imageUpload_Form", "Top View"))
        self.sideView_label.setText(_translate("imageUpload_Form", "Side View"))
        self.topUploadImage_pushButton.setText(_translate("imageUpload_Form", "Upload Image"))
        self.sideUploadImage_pushButton.setText(_translate("imageUpload_Form", "Upload Image"))
        self.UpLoad_pushButton.setText(_translate("imageUpload_Form", ""))
        self.Home_pushButton.setText(_translate("imageUpload_Form", ""))
        self.User_pushButton.setText(_translate("imageUpload_Form", ""))
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    imageUpload_Form = QtWidgets.QWidget()
    ui = Ui_imageUpload_Form()
    ui.setupUi(imageUpload_Form)
    imageUpload_Form.show()
    sys.exit(app.exec_())
