# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainW_Form(object):
    def setupUi(self, MainW_Form):
        MainW_Form.setObjectName("MainW_Form")
        MainW_Form.resize(1440, 900)
        self.label = QtWidgets.QLabel(MainW_Form)
        self.label.setGeometry(QtCore.QRect(121, 24, 298, 68))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainW_Form)
        self.label_2.setGeometry(QtCore.QRect(479, 87, 60, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(MainW_Form)
        self.pushButton.setGeometry(QtCore.QRect(106, 798, 213, 89))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(MainW_Form)
        self.pushButton_2.setGeometry(QtCore.QRect(601, 798, 213, 89))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(MainW_Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1121, 798, 213, 89))
        self.pushButton_3.setObjectName("pushButton_3")
        self.line = QtWidgets.QFrame(MainW_Form)
        self.line.setGeometry(QtCore.QRect(0, 792, 1440, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(MainW_Form)
        self.line_2.setGeometry(QtCore.QRect(720, 135, 3, 337))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(MainW_Form)
        QtCore.QMetaObject.connectSlotsByName(MainW_Form)

    def retranslateUi(self, MainW_Form):
        _translate = QtCore.QCoreApplication.translate
        MainW_Form.setWindowTitle(_translate("MainW_Form", "Form"))
        self.label.setText(_translate("MainW_Form", "TextLabel"))
        self.label_2.setText(_translate("MainW_Form", "TextLabel"))
        self.pushButton.setText(_translate("MainW_Form", "PushButton"))
        self.pushButton_2.setText(_translate("MainW_Form", "PushButton"))
        self.pushButton_3.setText(_translate("MainW_Form", "PushButton"))
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainW_Form = QtWidgets.QWidget()
    ui = Ui_MainW_Form()
    ui.setupUi(MainW_Form)
    MainW_Form.show()
    sys.exit(app.exec_())
