# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registro_SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Stylesheet_format import Stylesheet


class Ui_Register_Form(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(1440, 900)

        self.return_pushButton = QtWidgets.QPushButton(Register,icon = QtGui.QIcon(QtGui.QPixmap("PyQt_Images/Return_icon.svg")))
        self.return_pushButton.setGeometry(QtCore.QRect(20, 14, 69, 75))
        self.return_pushButton.setObjectName("return_pushButton")
        self.return_pushButton.setStyleSheet(Stylesheet)

        self.fillYourProfile_label = QtWidgets.QLabel(Register)
        self.fillYourProfile_label.setGeometry(QtCore.QRect(91, 21, 376, 69))
        self.fillYourProfile_label.setObjectName("fillYourProfile_label")
        self.fillYourProfile_label.setStyleSheet(Stylesheet)

        self.firstName_label = QtWidgets.QLabel(Register)
        self.firstName_label.setGeometry(QtCore.QRect(54, 143, 200, 16))
        self.firstName_label.setObjectName("firstName_label")
        self.firstName_label.setStyleSheet(Stylesheet)
        self.firstName_lineEdit = QtWidgets.QLineEdit(Register)
        self.firstName_lineEdit.setGeometry(QtCore.QRect(54, 163, 260, 36))
        self.firstName_lineEdit.setObjectName("firstName_lineEdit")
        self.firstName_lineEdit.setStyleSheet(Stylesheet)

        self.lastName_label = QtWidgets.QLabel(Register)
        self.lastName_label.setGeometry(QtCore.QRect(324, 143, 200, 16))
        self.lastName_label.setObjectName("lastName_label")
        self.lastName_label.setStyleSheet(Stylesheet)
        self.lastName_lineEdit = QtWidgets.QLineEdit(Register)
        self.lastName_lineEdit.setGeometry(QtCore.QRect(324, 163, 1061, 36))
        self.lastName_lineEdit.setObjectName("lastName_lineEdit")
        self.lastName_lineEdit.setStyleSheet(Stylesheet)

        self.Email_label = QtWidgets.QLabel(Register)
        self.Email_label.setGeometry(QtCore.QRect(55, 236, 200, 16))
        self.Email_label.setObjectName("Email_label")
        self.Email_label.setStyleSheet(Stylesheet)
        self.Email_lineEdit = QtWidgets.QLineEdit(Register)
        self.Email_lineEdit.setGeometry(QtCore.QRect(55, 256, 1331, 36))
        self.Email_lineEdit.setObjectName("Email_lineEdit")
        self.Email_lineEdit.setStyleSheet(Stylesheet)

        self.password_label = QtWidgets.QLabel(Register)
        self.password_label.setGeometry(QtCore.QRect(55, 329, 200, 16))
        self.password_label.setObjectName("password_label")
        self.password_label.setStyleSheet(Stylesheet)
        self.password_lineEdit = QtWidgets.QLineEdit(Register)
        self.password_lineEdit.setGeometry(QtCore.QRect(55, 349, 1331, 36))
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.password_lineEdit.setStyleSheet(Stylesheet)

        self.confirmPassword_label = QtWidgets.QLabel(Register)
        self.confirmPassword_label.setGeometry(QtCore.QRect(55, 422, 200, 16))
        self.confirmPassword_label.setObjectName("confirmPassword_label")
        self.confirmPassword_label.setStyleSheet(Stylesheet)
        self.confirmPassword_lineEdit = QtWidgets.QLineEdit(Register)
        self.confirmPassword_lineEdit.setGeometry(QtCore.QRect(55, 442, 1331, 36))
        self.confirmPassword_lineEdit.setObjectName("confirmPassword_lineEdit")
        self.confirmPassword_lineEdit.setStyleSheet(Stylesheet)

        self.numberofInvoice_label = QtWidgets.QLabel(Register)
        self.numberofInvoice_label.setGeometry(QtCore.QRect(55, 515, 200, 16))
        self.numberofInvoice_label.setObjectName("numberofInvoice_label")
        self.numberofInvoice_label.setStyleSheet(Stylesheet)
        self.numberofInvoice_lineEdit = QtWidgets.QLineEdit(Register)
        self.numberofInvoice_lineEdit.setGeometry(QtCore.QRect(55, 535, 1331, 36))
        self.numberofInvoice_lineEdit.setObjectName("numberofInvoice_lineEdit")
        self.numberofInvoice_lineEdit.setStyleSheet(Stylesheet)

        self.agreeTerms_checkBox = QtWidgets.QCheckBox(Register)
        self.agreeTerms_checkBox.setGeometry(QtCore.QRect(54, 642, 400, 20))
        self.agreeTerms_checkBox.setObjectName("agreeTerms_checkBox")
        self.agreeTerms_checkBox.setStyleSheet(Stylesheet)
        
        self.SignUp_pushButton = QtWidgets.QPushButton(Register)
        self.SignUp_pushButton.setGeometry(QtCore.QRect(28, 790, 1384, 44))
        self.SignUp_pushButton.setObjectName("signUp_pushButton")
        self.SignUp_pushButton.setStyleSheet(Stylesheet)

        self.haveAnAcount_label = QtWidgets.QLabel(Register)
        self.haveAnAcount_label.setGeometry(QtCore.QRect(591, 854, 170, 22))
        self.haveAnAcount_label.setObjectName("haveAnAcount_label")
        self.haveAnAcount_label.setStyleSheet(Stylesheet)
        
        self.signIn_pushButton = QtWidgets.QPushButton(Register)
        self.signIn_pushButton.setGeometry(QtCore.QRect(771, 854, 100, 22))
        self.signIn_pushButton.setObjectName("signIn_pushButton")
        self.signIn_pushButton.setStyleSheet(Stylesheet)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Form"))
        self.fillYourProfile_label.setText(_translate("Register", "Fill Your Profile"))
        self.firstName_label.setText(_translate("Register","First name"))
        self.firstName_lineEdit.setPlaceholderText(_translate("Login_Form", "Enter first name"))
        self.lastName_label.setText(_translate("Register","Last name"))
        self.lastName_lineEdit.setPlaceholderText(_translate("Login_Form", "Enter last name"))
        self.Email_label.setText(_translate("Register","Email"))
        self.Email_lineEdit.setPlaceholderText(_translate("Login_Form", "example.email@gmail.com"))
        self.password_label.setText(_translate("Register", "Password"))
        self.password_lineEdit.setPlaceholderText(_translate("Login_Form", "Enter at least 8+ characters"))
        self.confirmPassword_label.setText(_translate("Register","Confirm password"))
        self.confirmPassword_lineEdit.setPlaceholderText(_translate("Login_Form", "Enter at least 8+ characters"))
        self.numberofInvoice_label.setText(_translate("Register","Number of Invoice"))
        self.numberofInvoice_lineEdit.setPlaceholderText(_translate("Login_Form", "Enter at least 8+ characters"))
        self.agreeTerms_checkBox.setText(_translate("Register", "By signing up, I agree with the Terms of Use & Privacy Policy"))
        self.SignUp_pushButton.setText(_translate("Register", "Sign Up"))
        self.haveAnAcount_label.setText(_translate("Register", "Already have an account?"))
        self.signIn_pushButton.setText(_translate("Register", "Sign in"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Register = QtWidgets.QWidget()
    ui = Ui_Register_Form()
    ui.setupUi(Register)
    Register.show()
    sys.exit(app.exec_())
