# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubVentanaMestra.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageMat_Form(object):
    def setupUi(self, ImageMat_Form):
        ImageMat_Form.setObjectName("ImageMat_Form")
        ImageMat_Form.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(ImageMat_Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 40, 251, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Material_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Material_lineEdit.setObjectName("Material_lineEdit")
        self.gridLayout.addWidget(self.Material_lineEdit, 1, 1, 1, 1)
        self.Entrecruz_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.Entrecruz_spinBox.setObjectName("Entrecruz_spinBox")
        self.gridLayout.addWidget(self.Entrecruz_spinBox, 2, 1, 1, 1)
        self.MaterialMues_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.MaterialMues_label.setObjectName("MaterialMues_label")
        self.gridLayout.addWidget(self.MaterialMues_label, 1, 0, 1, 1)
        self.IDMues_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.IDMues_lineEdit.setObjectName("IDMues_lineEdit")
        self.gridLayout.addWidget(self.IDMues_lineEdit, 0, 1, 1, 1)
        self.IDMues_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.IDMues_label.setObjectName("IDMues_label")
        self.gridLayout.addWidget(self.IDMues_label, 0, 0, 1, 1)
        self.DimMat_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.DimMat_lineEdit.setObjectName("DimMat_lineEdit")
        self.gridLayout.addWidget(self.DimMat_lineEdit, 3, 1, 1, 1)
        self.DimMat_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.DimMat_label.setObjectName("DimMat_label")
        self.gridLayout.addWidget(self.DimMat_label, 3, 0, 1, 1)
        self.Entrecruz_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Entrecruz_label.setObjectName("Entrecruz_label")
        self.gridLayout.addWidget(self.Entrecruz_label, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ImageMat_Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 230, 251, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(ImageMat_Form)
        QtCore.QMetaObject.connectSlotsByName(ImageMat_Form)

    def retranslateUi(self, ImageMat_Form):
        _translate = QtCore.QCoreApplication.translate
        ImageMat_Form.setWindowTitle(_translate("ImageMat_Form", "Form"))
        self.MaterialMues_label.setText(_translate("ImageMat_Form", "Material"))
        self.IDMues_label.setText(_translate("ImageMat_Form", "ID: Muestra"))
        self.DimMat_label.setText(_translate("ImageMat_Form", "Dimenciones"))
        self.Entrecruz_label.setText(_translate("ImageMat_Form", "Entrecruzamiento"))
        self.pushButton_2.setText(_translate("ImageMat_Form", "Explorar"))
        self.pushButton.setText(_translate("ImageMat_Form", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImageMat_Form = QtWidgets.QWidget()
    ui = Ui_ImageMat_Form()
    ui.setupUi(ImageMat_Form)
    ImageMat_Form.show()
    sys.exit(app.exec_())
